/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author chemo
 */
public class VtnAsientos extends javax.swing.JFrame
{

    private java.util.List<JButton> asientosSeleccionados = new java.util.ArrayList<>();
    private JButton[][] asientos = new JButton[10][12];
    private boolean[][] ocupados = new boolean[10][12];

    /**
     * Creates new form VtnAsientos
     */
    public VtnAsientos()
    {
        initComponents();
        generarAsientosConPosicion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelAsientos = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAsientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("jButton2");
        panelAsientos.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        panelAsientos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, -1, -1));

        getContentPane().add(panelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        for (JButton asiento : asientosSeleccionados)
        {
            asiento.setBackground(Color.RED);  // Pintar de rojo los asientos seleccionados
        }

        //asientosSeleccionados.clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deseleccionarTodo()
    {
        for (int i = 0; i < 10; i++)
        {
            for (int j = 0; j < 12; j++)
            {
                if (!ocupados[i][j])
                {
                    asientos[i][j].setBackground(Color.LIGHT_GRAY);
                }
            }
        }
    }

    private void generarAsientosConPosicion()
    {
        int ancho = 20;
        int alto = 20;
        int espacio = 2;

        int desplazamientoX = 100;
        int desplazamientoY = 100;

        for (int fila = 0; fila < 10; fila++)
        {
            for (int col = 0; col < 45; col++)
            {
                JButton btn = new JButton();
                btn.setBackground(Color.LIGHT_GRAY);

                int x = desplazamientoX + col * (ancho + espacio);
                int y = desplazamientoY + fila * (alto + espacio);

                btn.addActionListener(new java.awt.event.ActionListener()
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                        if (btn.getBackground() == Color.LIGHT_GRAY)
                        {
                            btn.setBackground(Color.GREEN);
                            asientosSeleccionados.add(btn);
                        } else if (btn.getBackground() == Color.GREEN)
                        {
                            btn.setBackground(Color.LIGHT_GRAY);
                            asientosSeleccionados.remove(btn);
                        }
                    }
                });

                panelAsientos.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, ancho, alto));
            }
        }

        panelAsientos.revalidate();
        panelAsientos.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnAsientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panelAsientos;
    // End of variables declaration//GEN-END:variables
}
