/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import modelo.Boleto;

/**
 *
 * @author chemo
 */
public class VtnAsientos extends javax.swing.JInternalFrame
{

    private java.util.List<JButton> asientosSeleccionados = new java.util.ArrayList<>();
    private JButton[][] asientos = new JButton[10][12];
    private boolean[][] ocupados = new boolean[10][12];

    private final int filas = 10;
    private final int columnas = 45;
    private final Map<JButton, Boleto> mapaBoletos = new HashMap<>();
    private final Map<String, Double> precios = new HashMap<>();
    /**
     * Creates new form VtnAsientos
     */
    public VtnAsientos()
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        cargarPrecios();
        generarAsientosConPosicion();
    }

    private void cargarPrecios()
    {
        precios.put("VIP", 300.0);
        precios.put("Preferencial", 200.0);
        precios.put("General", 100.0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jButton2.setText("jButton2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void deseleccionarTodo()
    {
        for (JButton btn : asientosSeleccionados)
        {
            Boleto boleto = mapaBoletos.get(btn);
            String categoria = boleto.getCategoria();
            Color color = switch (categoria)
            {
                case "VIP" ->
                    Color.YELLOW;
                case "Preferencial" ->
                    Color.CYAN;
                default ->
                    Color.LIGHT_GRAY;
            };
            btn.setBackground(color);
        }
        asientosSeleccionados.clear();
    }

    private void generarAsientosConPosicion()
    {
        int ancho = 20;
        int alto = 20;
        int espacio = 2;

        int desplazamientoX = 100;
        int desplazamientoY = 100;

        double centroX = columnas / 2.0;
        double escalaBase = 0.25;

        for (int fila = 0; fila < filas; fila++)
        {
            for (int col = 0; col < columnas; col++)
            {
                JButton btn = new JButton();

                String categoria = (fila < 3) ? "VIP" : (fila < 6) ? "Preferencial" : "General";
                Color color = switch (categoria)
                {
                    case "VIP" ->
                        Color.YELLOW;
                    case "Preferencial" ->
                        Color.CYAN;
                    default ->
                        Color.LIGHT_GRAY;
                };

                btn.setBackground(color);
                btn.setOpaque(true);
                btn.setBorderPainted(false);

                double xRel = col - centroX;
                double curva = Math.pow(xRel, 2) * escalaBase * (1 + fila * 0.1);

                int x = desplazamientoX + col * (ancho + espacio);
                int y = desplazamientoY + fila * (alto + espacio) + (int) curva;

                String id = "F" + fila + "_C" + col;
                double precio = precios.get(categoria);
                Boleto boleto = new Boleto(id, categoria, precio, id);

                btn.setToolTipText("Asiento " + id + " | " + categoria + " $" + precio);

                btn.addActionListener(evt ->
                {
                    if (btn.getBackground() != Color.RED)
                    {
                        if (btn.getBackground() == Color.GREEN)
                        {
                            btn.setBackground(color);
                            asientosSeleccionados.remove(btn);
                        } else
                        {
                            btn.setBackground(Color.GREEN);
                            asientosSeleccionados.add(btn);
                        }
                    }
                });

                mapaBoletos.put(btn, boleto);
                panelAsientos.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, ancho, alto));
            }
        }

        panelAsientos.revalidate();
        panelAsientos.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
