/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import estructuras.ListarBoletos;
import estructuras.NodoCateg;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Boleto;
import modelo.*;

/**
 *
 * @author chemo
 */
public class VtnPrincipal extends javax.swing.JFrame
{

    private ListarBoletos nboleto = new ListarBoletos();

    private java.util.List<JButton> asientosSeleccionados = new java.util.ArrayList<>();
    private JButton[][] asientos = new JButton[10][12];
    private boolean[][] ocupados = new boolean[10][12];

    private final int filas = 10;
    private final int columnas = 45;
    private final Map<JButton, Boleto> mapaBoletos = new HashMap<>();
    private final Map<String, Double> precios = new HashMap<>();

    public static String correoSesion;

    /**
     * Creates new form VtnAsientos
     */
    public VtnPrincipal()
    {
        initComponents();
        //cargarPrecios();
        cargarCategorias();
        //generarAsientosConPosicion();
        menuInicio.setVisible(true);
        menuUbicacion.setVisible(true);
        menuSesion.setVisible(true);

        // Ocultar los demás
        menuBoletos.setVisible(false);
        menuMisCompras.setVisible(false);
        menuAdmin.setVisible(false);
        menuCerrarSesion.setVisible(false);

        if (correoSesion != null)
        {
            System.out.println("Sesión activa de: " + correoSesion);

            menuBoletos.setVisible(true);
            menuMisCompras.setVisible(true);
            menuAdmin.setVisible(false);
            menuSesion.setVisible(false);
            menuCerrarSesion.setVisible(true);
        }

        if ("admin".equalsIgnoreCase(correoSesion))
        {
            menuAdmin.setVisible(true);
        }
        setIconImage(getIconImage());

    }

    public Image getIconImage()
    {
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/Logo.png"));
        Image img = original.getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        return img;
    }
//
//    private void cargarPrecios()
//    {
//        precios.put("VIP", 300.0);
//        precios.put("Preferencial", 200.0);
//        precios.put("General", 100.0);
//    }

    private void cargarCategorias()
    {
        NodoCateg cat = new NodoCateg("VIP");
        System.out.println("Se creó categoría: " + cat.getCategoria());
        NodoCateg cat1 = new NodoCateg("Preferencial");
        System.out.println("Se creó categoría: " + cat1.getCategoria());
        NodoCateg cat2 = new NodoCateg("General");
        System.out.println("Se creó categoría: " + cat2.getCategoria());

        nboleto.agregarCategoria(cat);
        nboleto.agregarCategoria(cat1);
        nboleto.agregarCategoria(cat2);
        /*
        operaciones.mostrarCategoria("VIP");
        operaciones.mostrarCategoria("Preferencial");
        operaciones.mostrarCategoria("General");
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelControl = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuBoletos = new javax.swing.JMenu();
        menuUbicacion = new javax.swing.JMenu();
        menuMisCompras = new javax.swing.JMenu();
        menuAdmin = new javax.swing.JMenu();
        menuSesion = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadio Universitario Alberto \"Chivo\" Cordoba");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(130, 162, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UAEMEX.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estadio Universitario Alberto \"Chivo\" Córdoba");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 110));

        panelControl.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1300, 560));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagina-de-inicio.png"))); // NOI18N
        menuInicio.setText("Inicio");
        menuInicio.setToolTipText("");
        menuInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInicio);

        menuBoletos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boleto.png"))); // NOI18N
        menuBoletos.setText("Boletos");
        menuBoletos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuBoletos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuBoletosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBoletos);

        menuUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estadio.png"))); // NOI18N
        menuUbicacion.setText("Ubicacion Estadio");
        menuUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuUbicacion.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuUbicacionMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuUbicacion);

        menuMisCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito-de-supermercado.png"))); // NOI18N
        menuMisCompras.setText("Mis Compras");
        menuMisCompras.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuMisComprasMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuMisCompras);

        menuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/panel-de-administrador.png"))); // NOI18N
        menuAdmin.setText("Administrador");
        menuAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuAdmin.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuAdminMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAdmin);

        menuSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil-del-usuario.png"))); // NOI18N
        menuSesion.setText("Iniciar Sesion");
        menuSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuSesion.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSesion);

        menuCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        menuCerrarSesion.setText("Cerrar Sesion");
        menuCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuCerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCerrarSesion);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        panelControl.removeAll();
        VtnInicio inicio = new VtnInicio();
        panelControl.add(inicio).setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void menuBoletosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuBoletosMouseClicked
    {//GEN-HEADEREND:event_menuBoletosMouseClicked
        panelControl.removeAll();
        VtnAsientos asientos = new VtnAsientos(nboleto);
        panelControl.add(asientos).setVisible(true);
    }//GEN-LAST:event_menuBoletosMouseClicked

    private void menuUbicacionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuUbicacionMouseClicked
    {//GEN-HEADEREND:event_menuUbicacionMouseClicked
        panelControl.removeAll();
        VtnMapaEstadio mapa = new VtnMapaEstadio();
        panelControl.add(mapa).setVisible(true);
    }//GEN-LAST:event_menuUbicacionMouseClicked

    private void menuAdminMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuAdminMouseClicked
    {//GEN-HEADEREND:event_menuAdminMouseClicked
        panelControl.removeAll();
        VtnAdministrador admin = new VtnAdministrador();
        panelControl.add(admin).setVisible(true);
    }//GEN-LAST:event_menuAdminMouseClicked

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuInicioMouseClicked
    {//GEN-HEADEREND:event_menuInicioMouseClicked
        panelControl.removeAll();
        VtnInicio inicio = new VtnInicio();
        panelControl.add(inicio).setVisible(true);
    }//GEN-LAST:event_menuInicioMouseClicked

    private void menuSesionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuSesionMouseClicked
    {//GEN-HEADEREND:event_menuSesionMouseClicked
        dispose();
        new VtnLogin().setVisible(true);
    }//GEN-LAST:event_menuSesionMouseClicked

    private void menuMisComprasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuMisComprasMouseClicked
    {//GEN-HEADEREND:event_menuMisComprasMouseClicked
        panelControl.removeAll();
        VtnMostrarCompras compras = new VtnMostrarCompras();
        panelControl.add(compras).setVisible(true);
    }//GEN-LAST:event_menuMisComprasMouseClicked

    private void menuCerrarSesionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuCerrarSesionMouseClicked
    {//GEN-HEADEREND:event_menuCerrarSesionMouseClicked
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Deseas cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION)
        {
            panelControl.removeAll();
            panelControl.removeAll();
            panelControl.revalidate();
            panelControl.repaint();
            VtnInicio inicio = new VtnInicio();
            panelControl.add(inicio).setVisible(true);
            VtnPrincipal.correoSesion = null;

            menuBoletos.setVisible(false);
            menuMisCompras.setVisible(false);
            menuAdmin.setVisible(false);
            menuCerrarSesion.setVisible(false);

            menuSesion.setVisible(true);
            menuSesion.setText("Iniciar Sesión");

            JOptionPane.showMessageDialog(this, "Sesión cerrada correctamente.");
        }
    }//GEN-LAST:event_menuCerrarSesionMouseClicked

    private void deseleccionarTodo()
    {
        for (JButton btn : asientosSeleccionados)
        {
            Boleto boleto = mapaBoletos.get(btn);
            String categoria = boleto.getCategoria();
            Color color = switch (categoria)
            {
                case "VIP" ->
                    Color.YELLOW;
                case "Preferencial" ->
                    Color.CYAN;
                default ->
                    Color.LIGHT_GRAY;
            };
            btn.setBackground(color);
        }
        asientosSeleccionados.clear();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu menuAdmin;
    public javax.swing.JMenu menuBoletos;
    public javax.swing.JMenu menuCerrarSesion;
    private javax.swing.JMenu menuInicio;
    public javax.swing.JMenu menuMisCompras;
    public javax.swing.JMenu menuSesion;
    private javax.swing.JMenu menuUbicacion;
    private javax.swing.JDesktopPane panelControl;
    // End of variables declaration//GEN-END:variables
}
