/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import archivos.ManipulacionArchivos;
import cjb.ci.CtrlInterfaz;
import correo.EmailSender;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author chemo
 */
public class VtnRegistrarNuevoUsuario extends javax.swing.JFrame
{

    /**
     * Creates new form VtnRegistrarNuevoUsuario
     */
    public VtnRegistrarNuevoUsuario()
    {
        initComponents();
        setIconImage(getIconImage());
    }
    
    public Image getIconImage()
    {
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/Logo.png"));
        Image img = original.getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH);
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreJT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mostrarCheckBox = new javax.swing.JCheckBox();
        apellidoJT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        correoJT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contraseñaTF = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Cuenta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        nombreJT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(nombreJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 310, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("APELLIDO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ACEPTAR");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 120, -1));

        mostrarCheckBox.setText("Mostrar Contraseña");
        mostrarCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mostrarCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        apellidoJT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(apellidoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 310, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("CORREO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        correoJT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(correoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 310, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("CONTRASEÑA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        contraseñaTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(contraseñaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 350, 340));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UAEMEX.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        dispose();
        new VtnLogin().setVisible(true);
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mostrarCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mostrarCheckBoxActionPerformed
    {//GEN-HEADEREND:event_mostrarCheckBoxActionPerformed
        if (mostrarCheckBox.isSelected())
        {
            contraseñaTF.setEchoChar((char) 0);
        } else
        {
            contraseñaTF.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String nombre = nombreJT.getText().trim();
        String apellido = apellidoJT.getText().trim();
        String correo = correoJT.getText().trim();
        String contrasena = new String(contraseñaTF.getPassword()).trim();

        if (nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty() || contrasena.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        if (!correo.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,6}$"))
        {
            JOptionPane.showMessageDialog(this, "Correo electrónico no válido.");
            return;
        }

        ArrayList<Usuario> listaUsuarios = (ArrayList<Usuario>) ManipulacionArchivos.carga(this, "usuarios.dat");
        if (listaUsuarios == null)
        {
            listaUsuarios = new ArrayList<>();
        }

        for (Usuario u : listaUsuarios)
        {
            if (u.getCorreo().equalsIgnoreCase(correo))
            {
                JOptionPane.showMessageDialog(this, "Ya existe un usuario con ese correo.");
                return;
            }
        }

        String codigo = String.valueOf((int) (Math.random() * 900000) + 100000);

        String html = """
    <div style='font-family: Arial, sans-serif;'>
        <div style='text-align: center;'>
            <img src='cid:logoUAEMex' height='80'/><br><br>
            <h2 style='color: green;'>¡Verificación de cuenta para el Estadio Universitario Alberto "Chivo" Córdoba!</h2>
        </div>

        <p style='color: #d9534f; font-size: 16px;'>Este es tu código de verificación:</p>

        <div style='text-align: center; margin: 20px 0;'>
            <span style='font-size: 32px; font-weight: bold; color: #007bff; border: 2px dashed #007bff; padding: 10px 20px; border-radius: 10px;'>
                """ + codigo + """
            </span>
        </div>

        <p style='font-size: 14px;'>Por favor, ingresa este código en el formulario para completar tu registro.</p>
        <p style='font-size: 14px;'>Gracias por registrarte. ¡Te esperamos en el estadio!</p>

        <hr style='margin-top: 30px;'>
        <p style='font-size: small; color: gray;'>Este correo fue generado automáticamente. No respondas a este mensaje.</p>
    </div>
    """;

        EmailSender.enviarCorreo(correo, "🔐 Verificación de cuenta", html);

        DialogoCodigoConTiempo dialogo = new DialogoCodigoConTiempo(this);
        dialogo.setVisible(true);

        if (!dialogo.fueConfirmado() || !dialogo.getCodigoIngresado().equals(codigo))
        {
            JOptionPane.showMessageDialog(this, "Código incorrecto o tiempo expirado. Registro cancelado.");
            return;
        }

        Usuario nuevo = new Usuario(nombre, apellido, correo, contrasena);
        listaUsuarios.add(nuevo);
        ManipulacionArchivos.guarda(this, listaUsuarios, "usuarios.dat");

        JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.");
        CtrlInterfaz.limpia(nombreJT, apellidoJT, correoJT, contraseñaTF);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistrarNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistrarNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistrarNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistrarNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistrarNuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoJT;
    private javax.swing.JPasswordField contraseñaTF;
    private javax.swing.JTextField correoJT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox mostrarCheckBox;
    private javax.swing.JTextField nombreJT;
    // End of variables declaration//GEN-END:variables
}
